Fix: Types Typo
facebook/flipper pull request #1255
Opened 2020-06-15 11:41 UTC by zusinShinpei

## Summary

## Changelog

## Test Plan

2020-06-18 15:38 UTC, jknoxville commented on desktop/doctor/src/index.ts
> +              } not installed or not added to PATH. ${result.message}.`,
I don't think this message makes sense now:

When hasProblem:
`OpenSSL is not not installed or not added to PATH.`

When !hasProblem:
`OpenSSL is not installed or not added to PATH.`

2020-06-18 15:41 UTC, jknoxville commented on desktop/doctor/src/index.ts
> +              } installed or not added to PATH. Live reloading after changes during Flipper plugin development is disabled.`,
Same here.

2020-10-06 10:06 UTC, mweststrate requested changes
Hi @zusinShinpei, do you still intend to follow up on the review comments? If not, then best close the PR. Thanks!

2020-10-09 08:03 UTC, mweststrate commented
Closing for inactivity

2020-10-09 08:03 UTC, closed without merging