Adding Brotli compression support
facebook/flipper pull request #4288
Opened 2022-10-31 17:30 UTC by dallasgutauckis

Closes #2578

## Summary

Adds Brotli compression support for br-encoded endpoints

## Changelog

 - Brotli compression support

## Test Plan

Confirmed `content-encoding` had `br` for Brotli and that the response text post-decompression was parsed properly:

![image](https://user-images.githubusercontent.com/117083/199068874-1577577f-2d2f-4687-a3d8-aa41a032ab32.png)
![image](https://user-images.githubusercontent.com/117083/199069109-8564ea03-99db-4c8a-9dbc-4d007fe38f5b.png)

A note for reviewer(s) is that I am by no means a javascript/typescript/yarn/npm/electron/etc developer, so please please make sure I did things properly and let me know what to fix, how, why it's wrong. Thanks!

2022-11-15 07:54 UTC, mweststrate requested changes
Thanks for making this PR! Most of it looks good, but would you mind reverting the changes in desktop/package.json and desktop/yarn.lock, those changes look unrelated an unneeded. Not sure if the were intentional?

Thanks!

2022-11-18 21:06 UTC, dallasgutauckis commented
@mweststrate I'm quite naive as previously mentioned, so I removed these changes but ran `yarn` and `yarn start` as per `README.md` and it added changes to `desktop/plugins/public/yarn.lock` still. If those are not necessary, please let me know and I'll be happy to fix that as well.

2022-12-12 15:48 UTC, dallasgutauckis commented
@mweststrate what do I do now?

2022-12-13 08:40 UTC, mweststrate commented
@dallasgutauckis sorry forgot about this one! I tried merging yesterday, but it seems the unit tests are failing, mind looking into that? `yarn test --watch` in desktop folder, use filter 'network'.

2022-12-13 08:40 UTC, mweststrate requested changes
Unit tests are failing

2022-12-14 16:43 UTC, dallasgutauckis commented
@mweststrate we were missing a break statement needed to exit out of the switch statement instead of falling through to the brotli case. Mind giving this another go?

2022-12-15 15:41 UTC, mweststrate commented
Sure!

2022-12-15 17:40 UTC, mweststrate commented
Let me try it here first, it can be internal caches.

On Thu, 15 Dec 2022, 18:00 Dallas Gutauckis, ***@***.***>
wrote:

> I see there's other stuff going on with importing the pull request. Do you
> want me to click the rebase button or are you just merging it on your side
> and pushing up into here? @mweststrate <https://github.com/mweststrate>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/facebook/flipper/pull/4288#issuecomment-1353405066>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAN4NBECS3ETMVBCAJNUW3LWNNFEHANCNFSM6AAAAAARTJTRFE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-16 09:47 UTC, mweststrate commented
Seems all ok  now, landing! Will be part of the next release. (might be in the new year, not sure if there will be a release next week). Thanks for putting up this functionality in any case!

2022-12-16 10:43 UTC, closed without merging